### ISSUE TITLE
search.js Promise undefined

### ISSUE THREAD

**Issue by fusiller** [tdurieux/leboncoin-api#1]
Nice work ! Congratulations and thanks for sharing.
Just trying to use it this morning.
So far only used Search. Seems to me that
const Promise = require('pinkie-promise');
is necessary in search.js.
Also npm install pinkie-promise at the leboncoin-api directory level

**Comment by tdurieux** [comment]
Tanks.

In Node 5.0.0, Promise exists natively.
I can add this dependencies to be backward compatible.

**Comment by fusiller** [comment]
Oops. Running v0.10.17 on OS X, sorry. Good time to upgrade :)
