### ISSUE TITLE
limitation information

### ISSUE THREAD

**Issue by lalop** [tdurieux/leboncoin-api#10]
This is not really an issue but it's the only place I found to post my question.

While trying your library, I get `Cannot retrieve the phone number URI. You may exceed your API quota.
` 
Do you know what can I do to be back under the quota ?
Is it during a time window ?

Thank you

**Comment by tdurieux** [comment]
This error has two possible origins:
1. The author of the announce did not provide a phone number
2. You reach your quota

You probably can reset your quota by changing your IP or wait (but I don't know when the quota is reseted, at least once per day).
