### ISSUE TITLE
Simplify by using phone number json api

### ISSUE THREAD

**Issue by fmassot** [tdurieux/leboncoin-api#11]
Just a suggestion as there is a json api
```
curl 'https://api.leboncoin.fr/api/utils/phonenumber.json' -H 'Origin: https://www.leboncoin.fr' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8,fr;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: _/_' -H 'Referer: https://www.leboncoin.fr/ventes_immobilieres/986418621.htm?ca=12_s' -H 'Connection: keep-alive' --data 'list_id=986418621&app_id=leboncoin_web_utils&key=54bb0281238b45a03f0ee695f73e704f&text=1' --compressed
```
returns: 

{"utils":{"status":"OK","phonenumber":"0664104902"}}

**Comment by tdurieux** [comment]
Hi, 
Sorry to answer quiet late...
I'm not a bug fan of using someone else api key. 
This library is already border line, I don't went to use q private api.
The best solution is may be contact leboncoin but I don't have neither a lot of time nor use of this library

**Comment by CharlesCollas** [comment]
Actually it's not someone else's api key, I admit it's strange but if you check on their website by opening your developer tools in your browser and searching for "apiKey" you'll find: `var apiKey = "54bb0281238b45a03f0ee695f73e704f";` between script tags. It's always this one.
