### ISSUE TITLE
Search - Set the url

### ISSUE THREAD

**Issue by JulienMalige** [tdurieux/leboncoin-api#12]
I'm using your JS API for a project. I already have the URLs of leboncoin queries.

What do you think about adding a setUrl() to the Search ? 
I just check in getUrl() if an URL is already defined. If it is I return it, if it isn't, I build an URL (initial way).

I can propose a pull request.

**Comment by tdurieux** [comment]
I publish the version v0.0.10 which allow you to run a search with a specific url:
```js
var url = 'http://www.leboncoin.fr/ventes_immobilieres/offres/...';
new leboncoin.Search().run(url).then(function (data) {
  console.log(data);
});
``` 
If url is null, the library will use the previous API.

Is it ok for you?

**Comment by JulienMalige** [comment]
Works for me ! 👍 
thanks

**Comment by maximelebreton** [comment]
hello @tdurieux, and thanks for this amazing work!

I tried this in v`0.0.35`
```node
var url = "https://www.leboncoin.fr/recherche/?category=4&text=caravane";
  new leboncoin.Search().run(url).then(function(data) {
    console.log(data);
  });
```

but it seems broken:


```node
error: undefined:1
<!--
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (node_modules\leboncoin-api\lib\search.js:390:47)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

thanks for your help!

**Comment by tdurieux** [comment]
Hello @maximelebreton 

Unfortunately, this feature is not available anymore since leboncoin changes it API.

**Comment by maximelebreton** [comment]
Okay, so I'll made a reverse feature (and maybe a pull request if it's good enough!)

Thanks for you answer

**Comment by maximelebreton** [comment]
Prototype started here if you want to take a look: https://codesandbox.io/s/vnj74qmol5

**Comment by tdurieux** [comment]
Seems good, can you open a PR?

Thanks

**Comment by maximelebreton** [comment]
Hello @tdurieux, I've finally create a standalone package, because it doesn't have depedencies with `leboncoin-api`, and can be reusable in other contexts:  
https://github.com/maximelebreton/leboncoin-reverse-url _(sorry about this unclear package name, if any better idea...)_

So it doesn't need a PR, here is a working example:

```js
const leboncoin = require('leboncoin-api');
const reverseUrl = require('leboncoin-reverse-url');

var url = "https://www.leboncoin.fr/recherche/?category=4&text=caravane";
const bodyParams = reverseUrl(url);

new leboncoin.Search().run(null, bodyParams).then(function(data) {
  console.log(data);
});
```

But feel free to implement it in your codebase!
