### ISSUE TITLE
Publish typings

### ISSUE THREAD

**Issue by Supamiu** [tdurieux/leboncoin-api#14]
I'm working on a simple application using nodejs and your library, therefore I'd like to create it using typescript, in order to do that, i'd need typings of this library.

If you don't know how to create typings, I can do it for you in @types repository but I'll need a list of methods with their signature.

**Comment by AurelienC** [comment]
Hello,

You could find all information into [source files](https://github.com/tdurieux/leboncoin-api/tree/master/lib).

👍

**Comment by tdurieux** [comment]
I published a website with the documentation to use the library here: https://durieux.me/projects/leboncoin.html
