### ISSUE TITLE
Parseseller doesn't work when professional items

### ISSUE THREAD

**Issue by Alexandre3721** [tdurieux/leboncoin-api#16]
Instead of a "title" class it's a "panelTitle" class 

You use this code for parseSeller in item.js : 
return cleanString($(".mbs > .title").html().trim());

But for professional items (i don't know if it's the case for every the professional item) the html code looks like this :
<img width="579" alt="capture d ecran 2017-09-22 a 13 03 53" src="https://user-images.githubusercontent.com/32195538/30741772-871dd4ee-9f96-11e7-9c00-556a8faf72bc.png">

Great work by the way ;)

**Comment by tdurieux** [comment]
Thanks @Alexandre3721
