### ISSUE TITLE
Shared Search Extras

### ISSUE THREAD

**Issue by ovmjm** [tdurieux/leboncoin-api#18]
Thanks Thomas for this usefull library.

When creating and running two searchs, I found out the second `Search` object inherited of `searchExtras` values from the first one.

This seems to be due to the way `searchExtras` field is initialized.

Maybe I'm wrong but I suggest not to create `searchExtras` this way : 

    Search.prototype.searchExtras = {};

but this way : 

    const Search = function (options) {
        ...
        this.searchExtras = {};
        ...
    }

I think you should do the same for all fields. Putting fields in the prototype is only usefull if you plan to share them between most of your instances (this is mostly what you want for functions but not for data).

**Comment by tdurieux** [comment]
Thanks @ovmjm
