### ISSUE TITLE
Search not returning results

### ISSUE THREAD

**Issue by RodolpheGohard** [tdurieux/leboncoin-api#21]
Hello,

my code using leboncoin-api have started to fail about a week ago, I wonder if there has been an API change:

```
const leboncoin = require('leboncoin-api');
var search = new leboncoin.Search()
    .setPage(1)
    .setQuery('clavier')
    .setFilter(leboncoin.FILTERS.PARTICULIER)
    .setCategory("instruments_de_musique")
    .setRegion("ile_de_france");

search.run().then(function (data) {
    console.log(data.page); // the current page
    console.log(data.nbResult); // the number of results for this search
    console.log(data.results); // the array of results
}, function (err) {
    console.error(err);
});
```

returns no results:
```
PS C:\Users\redacted.r\dev\adsvisor> node .\testlbc.js
1
NaN
[]
```

I was pretty sure it worked two weeks ago.

When I run the search manually, there are results to this request. Also, when I look at the network, I see the results are fed from a REST API which I think wasn't there before. Has there been a revamp ?

**Comment by tdurieux** [comment]
The search behavior of leboncoin changes completely for some category.
I need to rewrite completely the search but I'm pretty busy right now:/

The release 0.0.18 partially fix the problem :/

**Comment by 7hibault** [comment]
There's an issue here: https://github.com/tdurieux/leboncoin-api/blob/master/lib/search.js#L140

When we set a region, a '/' gets inserted in the pathname, but we keep on inserting them afterwards and end up with pathnames like  https://www.leboncoin.fr/annonces/offres/rhone_alpes//ain

**Comment by 7hibault** [comment]
Maybe that'll fix @RodolpheGohard 's isue?

**Comment by tdurieux** [comment]
Unfortunately not.

I'm aware of the issue, the search is broken for some categories because leboncoin changed the url of the research for categories (transition period?).

**Comment by Mystou** [comment]
Do you talk about the missing "FLUX_STATE" in some page (/vi/ category for me) ?

**Comment by tdurieux** [comment]
I was talking about the new research page of leboncoint: https://www.leboncoin.fr/recherche/?text=t&category=66&region=17

The old research worked for some categories, now it seems that it is down for all the categories.

**Comment by tdurieux** [comment]
## new search api

https://api.leboncoin.fr/finder/search

Headers
``` 
Cookies
X-DataDome: protected
X-Unique-Id: <id>
```

body: 
```js
{"filters":{"category":{"id":"43"},"enums":{"ad_type":["offer"]},"keywords":{"text":"t"},"location":{"city_zipcodes":[{"city":"Lille","zipcode":"59000","label":"Lille (59000)"}],"region":"17"},"ranges":{}},"limit":35,"limit_alu":3}
```

## Categories

https://api.leboncoin.fr/api/parrot/v1/config/categories

## Subcategories

https://api.leboncoin.fr/api/parrot/v1/config/categories/searchparams

## Departments
https://api.leboncoin.fr/api/parrot/v1/config/departments

## Regions

https://api.leboncoin.fr/api/parrot/v1/config/regions

## Details

https://api.leboncoin.fr/finder/classified/1181659598

headers:
``` 
Cookies
X-DataDome: protected
X-Unique-Id: <id>
```

**Comment by RodolpheGohard** [comment]
Hello, thanks for looking into the issue.

I will try to investigate the issue myself but I do not have much available time as well

**Comment by soueuls** [comment]
I am interested helping reverse this API, I am getting started in real estate investment in France and I thought of building a tool to combine this API and Twilio to contact and aggressively negotiate the price of properties.

The new API seems to allow filtering by city name, which is not really possible with the old one I assume,

do you mind sharing a bit more information about how to correctly setup headers/cookies so I can play a bit with it and start writing some code?

**Comment by tdurieux** [comment]
I don't really know yet how to setup the header to get a response. You can get the info by looking the request from your browser

**Comment by soueuls** [comment]
I have been looking at the different APIs you listed, first of all great job!
department and regions seems straightforward, we need to put some kind a basic priority algorithm into place though in case the request contains all of them.

subcategories key are highly dependent on the category choosen and this will be hard to explain in a documentation, it would be nice to be able to fill them by labels too. Maybe develop a GUI query builder which correctly translate into the correct `new leboncoin.Search()`?

I have not yet figured out how to make the `finder/search` API to return some results, but I have good hope we might be able to get the phone number without relying on OCR

**Comment by tdurieux** [comment]
Since 0.0.15 (I think), I dont use ocr for the phone number. But I have to check if the Api is still valid. I m currently living outside France and this api is completely blocked for me :/

**Comment by soueuls** [comment]
I will live in France for the next 6 months or so at least, I do have some time, I can help you rewrite part of it so it's compatible with the new API.

Maybe you could list some features you would like to see being implemented and the general direction you want this package to take?

**Comment by tdurieux** [comment]
Honestly, I don't use this repository anymore. I just maintain it for the community.
The users should explain thier requirements.
But I think we should keep the compatibility with the currentstate of the api

**Comment by tdurieux** [comment]
The version 0.0.20 contains a temporary fix for the search.
I hope it will be good enough for the moment.

**Comment by myrevers** [comment]
@tdurieux 
Hello ! I found a solution to get results from the new leboncoin api.
I create a repo to allow you to test it using "node server.js" command:
https://github.com/myrevers/leboncoin-api-sample

Header details is under search.js file.

Hope this will help us to find a solution and apply related changes on your repository.

**Comment by ronyrun** [comment]
@myrevers I tried with postman and got a err 400 bad request : 

![image](https://user-images.githubusercontent.com/7273443/42421139-fd70bd32-82d0-11e8-894b-ac619d4099bd.png)

Do you have any clues ?

Ron

**Comment by tdurieux** [comment]
With the new release 0.0.31, this issue should solve. 
Thanks, everyone for the feedback.
