### ISSUE TITLE
API leboncoin not returning result anymore since 1 week

### ISSUE THREAD

**Issue by RomainBoy** [tdurieux/leboncoin-api#22]
app.get('/api/leboncoin', (req, res) => {
        var search = new leboncoin.Search()
            .setPage(1)
            .setQuery("106 s16")
           // .setFilter(leboncoin.FILTERS.PROFESSIONNELS)
            //.setCategory("voitures")
            .setRegion("ile_de_france")
            .addSearchExtra("mrs", 800) // min rent
            .addSearchExtra("mre", 40000); // min rent

        search.run().then(function (data) {
            console.log(data.page); // the current page
            console.log(data.nbResult); // the number of results for this search
            console.log(data.results); // the array of results

             res.send({results: {data}})

            // data.results[0].getDetails().then(function (details) {
            //     res.send({results: {details}})

            //     console.log(details); // the item 0 with more data such as description, all images, author, ...
            // }, function (err) {
            //     console.error(err);
            // });
            // data.results[0].getPhoneNumber().then(function (phoneNumer) {
            //     console.log(phoneNumer); // the phone number of the author if available
            // }, function (err) {
            //     console.error(err); // if the phone number is not available or not parsable (image -> string) 
            // });
        }, function (err) {
            console.error(err);
        });
  });

Result on server -> 
 1
 NaN
 []

Result in browser ->
{"results":{"data":{"page":1,"nbResult":null,"results":[]}}}

**Comment by tdurieux** [comment]
the version 0.0.31 should fix this issue.
