### ISSUE TITLE
Problems with API

### ISSUE THREAD

**Issue by andreaangeli** [tdurieux/leboncoin-api#28]
I tried to run this script

```js
const leboncoin = require('leboncoin-api');
var search = new leboncoin.Search()
.setPage(1) //ricercare nella pagina
.setQuery('velo') //cosa cercare
.setFilter(leboncoin.FILTERS.PARTICULIER) // PROFESSIONNELS oppure ALL
.setCategory("locations") //categoria di ricerca
.setRegion("alsace") // regione di ricerca
.setDepartment("Bas-rhin")
.setLocation("Colmar")
.addSearchExtra("price", {min: 200, max: 400}) // will add a range of price
//.addSearchExtra('furnished', ["1", "Non meublé"]);

search.run().then(function (data) {
console.log(data.page); // the current page
console.log(data.nbResult); // the number of results for this search
console.log(data.results); // the array of results
}, function (err) {
console.error(err);
});`
but returns always

1 NaN []
```
That's strange because some days ago it worked well

**Comment by andreaangeli** [comment]
I tried to run this script 

`const leboncoin = require('leboncoin-api');
var search = new leboncoin.Search()
    .setPage(1) //ricercare nella pagina
    .setQuery('velo') //cosa cercare
    .setFilter(leboncoin.FILTERS.PARTICULIER)  // PROFESSIONNELS oppure ALL 
    .setCategory("locations") //categoria di ricerca
    .setRegion("alsace") // regione di ricerca
    .setDepartment("Bas-rhin")
    .setLocation("Colmar")
    .addSearchExtra("price", {min: 200, max: 400}) // will add a range of price
    //.addSearchExtra('furnished', ["1", "Non meublé"]);

search.run().then(function (data) {
    console.log(data.page); // the current page
    console.log(data.nbResult); // the number of results for this search
    console.log(data.results); // the array of results
}, function (err) {
    console.error(err);
});
`
but returns always 

`1
NaN
[]`

That's strange because some days ago it worked well

**Comment by tdurieux** [comment]
which version of the API do you use?

**Comment by RodolpheGohard** [comment]
same here,  using leboncoin-api@0.0.20

**Comment by tdurieux** [comment]
Leboncoin changed its website, this version does not work anymore. You have to use the latest one.

**Comment by andreaangeli** [comment]
sorry, I got wrong I updated the module and it works. By the way is there any command to download the results of the research in a formatted json file or CSV ? For instance I tried with the command `node research.js > output.json` and effectively it returns a file called output.json with the results but probably, the file is not properly formatted because I'm not able to open it as a json file.

**Comment by grandemk** [comment]
@andreaangeli Use console.log(JSON.stringify(data.results)); console.log alone doesn't format the result in json.
