### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by fusiller** [tdurieux/leboncoin-api#3]
Thanks a lot Thomas for this convenient API.
You may let us add "raw" query component to address category specific features, like for instance the brand for a car search or many other examples you may find in the numerous categories in Leboncoin.fr
Best regards,
Alex

**Comment by tdurieux** [comment]
Yes, it is planned.

**Comment by tdurieux** [comment]
close with 485e3900b55d609c2d14336d107887321f79d5fe
