### ISSUE TITLE
Problem with SetFilters Private - Pro

### ISSUE THREAD

**Issue by vincentdlrm** [tdurieux/leboncoin-api#35]
Hi,

Thanks for the work : the Api looks great ! I have just begun to test it.

I ve got trouble using the Filters to get content only from PROFESSIONEL or PARTICULIER.

It doesn't matter which value I pass through setFilters() : i get the same content (=understand private & pro in the result).

I used the sample code you provide in the readme file.
 .setFilter(leboncoin.FILTERS.PARTICULIER) send me back Pro & Private content.

Am I missing something ?

**Comment by tdurieux** [comment]
Hi @vincentdlrm,

Sorry to answer so late, we had a regression in the API and the filter was not taking into account.
I created a new release with this fix: 0.0.35. It should work now.

Thank you for the report :)

**Comment by vincentdlrm** [comment]
Top ! 
thanks
