### ISSUE TITLE
[Question] Use search Around me with custom location

### ISSUE THREAD

**Issue by foufrix** [tdurieux/leboncoin-api#36]
Do you think it would be possible to use the function search around me (which is present on the app) with custom location and range ? I can help to make the code if it's possible.

**Comment by tdurieux** [comment]
Hi @foufrix ,

Thank you for your interest.

I found a way to do it. I will try to implement it this week.

Rember for myself:
```js
{"filters":{"category":{},"enums":{"ad_type":["offer"]},"keywords":{},"location":{"area":{"lat":00.0000,"lng":0.0000,"radius":30000}},"ranges":{}},"limit":35,"limit_alu":3}
```

**Comment by tdurieux** [comment]
Sorry it is already supported.

```js
new Search().setArea({
  "lat":00.0000,
  "lng":0.0000,
  "radius":30000 // radius in meter
});
```

**Comment by foufrix** [comment]
Nice enhancement, sorry for the delay of respond, i'm gonna try it !
