### ISSUE TITLE
Empty results => example code fail

### ISSUE THREAD

**Issue by ErnestBrandi** [tdurieux/leboncoin-api#38]
Hi,
first you should talk about the lodash dependency, had to install manually (`Error: Cannot find module 'lodash'`).
Then when I try the given example from the Readme, I get
`(node:12192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getDetails' of undefined at C:\...\index.js:23:21
`
which basically means that I get no data back. Does someone else experience that with the latest version? 
Thanks !

**Comment by tdurieux** [comment]
The example is not well written, it was more an example how to use the library than really a working example (I don't check data contains at least one result). 

In order to make it work, you need to increase the price interval, renting in the 78 is expensive :)

**Comment by ErnestBrandi** [comment]
Thanks, I should have spent more time playing with the code, but sometimes in spend hours doing it with no result when it's obvious for the admin... It works great acutally, thank you for that code :)
