### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by dragma** [tdurieux/leboncoin-api#39]
My question will be simple. 
Since there aren't much documentation on leboncoin API, I believe their API is made for private usage only. Is this package compliant with leboncoin TOS ? Can it be used on a tierce application ?
Regards,
Florent

**Comment by tdurieux** [comment]
> Tout Utilisateur et Annonceur du Service LEBONCOIN s'engagent notamment à ne pas :
> extraire, à des fins commerciales ou non, tout ou partie des informations ou des petites Annonces présentes sur le Service LEBONCOIN et sur le Site et les Applications ;

Malheusement aucune utilisation des données du boncoin n'est autorisé.
(Mais c'est une pratique largement pratiquée par entre autre les agences imobilières .)

**Comment by dragma** [comment]
Je vois. Je vis m'en servir, on verra bien !
Merci encore pour le repo !
