### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by foufrix** [tdurieux/leboncoin-api#41]
Hello, merci pour ton repo il est top.

Petit problème survenu depuis peu (je ne serai pas dire exactement quand) mais mes requêtes sont bloquées. Je n'ai pas touché à mon code qui avant fonctionnait :/
Sais-tu d'où cela pourrai venir ? Fortification de l'api leboncoin ?
Merci d'avance :)

(Je suis bien sur la dernière version en 0.0.35

![image](https://user-images.githubusercontent.com/16646581/51387379-22ea5300-1b26-11e9-8257-488c0893359c.png)

**Comment by Rebolon** [comment]
Bonjour,
je n'utilise (encore) pas cette lib, mais le problème vient du serveur du boncoin. Ils ont mis en place des CORS (bizarre que cela n'ai pas été mis en place avant...) qui bloque l'accès à leur resource depuis une page qui n'est pas sur https?://www.leboncoin.fr
La solution, comme évoqué par @tdurieux est de passer par nodejs. Côté serveur, il n'y a plus de CORS possible. Attention toutefois: analysez bien les requêtes faites depuis leboncoin vers leur serveur afin de définir correctement les headers (cookies inclus) et ainsi limiter les risque de se faire blacklister

**Comment by dawadam** [comment]
Bonjour, effectivement, on ne peut pas utiliser la bibliothèque coté navigateur (c'est la première fois que je rédige en Français sur gitHub, ça fait bizarre).
Le code étant bien fait, on peut récupérer les données correspondantes à la requête et exécuter une requête partant de ces données. C'est idéale pour être utilisée conjointement coté navigateur (pour générer l'objet) et coté serveur nodejs (pour exécuter la requête).

Coté navigateur :
```
       var search = new leboncoin.Search()
            .setPage(1)
            .setQuery("renove")
            .setFilter(leboncoin.FILTERS.PARTICULIER)
            .setCategory("locations")
            .setRegion("ile_de_france")
            .setDepartment("yvelines")
            .setLocation([
                { "zipcode": "78100" },
                { "zipcode": "78000" },
            ])
            .addSearchExtra("price", { min: 1500, max: 2000 }) // will add a range of price
            .addSearchExtra('furnished', ["1", "Non meublé"]); // will add enums for Meublé and Non meublé

            var bodyParams = search.getBodyParams()

            // transmettre les paramètres au serveur nodejs
            // TODO
```

Coté serveur nodejs
```
// récupérer les paramètres de la requête cliennt
// TODO

 search.run(null, bodyParams)
            .then(function (data) {

            // transmettre la réponse au navigateur
            // TODO

        }, function (err) {
            console.error(err);
        });
```
Avec tout de même l'inconvéniant de ne pas pouvoir utiliser les fonctions de récuération de détail et de numéro de téléphone dynamiquement coté navigateur, puisqu'il faut les utiliser coté serveur avant de retourner la réponse au navigateur.

**Comment by alainib** [comment]
bonsoir.
J'ai aussi un blocage CORS sous nodejs 


    var search = new leboncoin.Search().setPage(page).setQuery(queryUrl).setFilter(leboncoin.FILTERS.PARTICULIER);
	
	search.run().then(
         function (data) {
			console.log(data.page); // the current page
			console.log(data.pages); // the number of pages
			console.log(data.nbResult); // the number of results for this search
			console.log(data.results); 
		}
	);


avez vous une solution ?
merci

**Comment by dawadam** [comment]
Vous pouvez postez le message d'erreur pour voir.
