### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by dawadam** [tdurieux/leboncoin-api#45]
Bonjour,
Il y a un souci lorsqu'on veut faire une recherche avec un filtre de prix, en sélectionnant une catégorie principale (et non pas une sous-catégorie).

```
// paramètres
 var search = new leboncoin.Search()
  .setQuery("test")
  .setCategory("8") // immobilier
  search.addSearchExtra("price", { min: 0, max: 5000 })
  var bodyParams = search.getBodyParams();

  // recherche
  var search = new leboncoin.Search()
  search.run(null, bodyParams)
```
L'erreur étant :

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _.forEach (/node_modules/leboncoin-api/lib/search.js:271:26)
```
Merci

**Comment by tdurieux** [comment]
Bonjour,

Il faut remplacer `.setCategory("8")` par `.setCategory(" _immobilier_")`.

Les labels sont disponibles ici: https://github.com/tdurieux/leboncoin-api/blob/master/const/categories.json

**Comment by dawadam** [comment]
Ça veut dire que dans le cas des sous-catégories, on peut passer l'identifiant, mais pas dans le cas des catégories.
Est-ce qu'on peut passer le label dans le cas des sous-catégories ? Car si oui, autant se passer des identifiants.

ps: ce serait pratique d'intégrée une référence aux catégories issues du fichier json dans le module

**Comment by dawadam** [comment]
Je viens de tester en utilisant le channel, sans succès.

```
 var search = new leboncoin.Search()
  .setQuery("test")
  .setCategory("_immobilier_")
  search.addSearchExtra("price", { min: 0, max: 5000 })
  var bodyParams = search.getBodyParams();
```

Pas d'erreur, mais pas de filtration.

**Comment by sylvain-d** [comment]
Hello,
De base sur le site du bon coin le filtrage par prix n'est pas disponible pour les catégories "générale"
![image](https://user-images.githubusercontent.com/490466/56061407-a1434380-5d69-11e9-9965-099bf2f51fae.png)
Je dirais donc que c'est le fonctionnement normal de l'API.

Sur une sous catégorie, le filtrage avancé est par contre disponible.
![image](https://user-images.githubusercontent.com/490466/56061465-c6d04d00-5d69-11e9-8f67-bf754384163f.png)

**Comment by tdurieux** [comment]
Ca fonctionnait dans la version précédente du site. Ca fait lontemps que je n utilise plus cette lib, je vais y regarder de plus près.

**Comment by dawadam** [comment]
@sylvain-d je veux bien que le filtrage de prix ne fonctionne pas pour une catégorie principale, mais de là à déclancher une telle erreur...
