### ISSUE TITLE
API down ? 

### ISSUE THREAD

**Issue by gchapelle** [tdurieux/leboncoin-api#55]
Hi,
Does the API still work for you? 
I did a small script from python using
https://api.leboncoin.fr/finder/search/'
which does not seem to work anymore ?
Thanks 

Best

Guillaume

**Comment by alexismoreau** [comment]
I have this error :

> /app/node_modules/leboncoin-api/lib/item.js:80
>            self.images = entry.images.urls;
>                                        ^
>  TypeError: Cannot read property 'urls' of undefined
>      at Request._callback (/app/node_modules/leboncoin-api/lib/item.js:80:40)
>      at Request.self.callback (/app/node_modules/request/request.js:185:22)
>      at emitTwo (events.js:126:13)
>      at Request.emit (events.js:214:7)
>      at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
>      at emitOne (events.js:116:13)
>      at Request.emit (events.js:211:7)
>      at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
>      at Object.onceWrapper (events.js:313:30)
>      at emitNone (events.js:111:20)
>      at IncomingMessage.emit (events.js:208:7)
>      at endReadableNT (_stream_readable.js:1064:12)
>      at _combinedTickCallback (internal/process/next_tick.js:139:11)
>      at process._tickCallback (internal/process/next_tick.js:181:9)
>

**Comment by alexismoreau** [comment]
It looks like it's working again,
I suggest changing 
https://github.com/tdurieux/leboncoin-api/blob/5280d9ae90e48f1fc9e7f94f4708dd8e9756512a/lib/search.js#L368
to 
`images: (entry.images && entry.images.urls && entry.images.urls) || [],`

**Comment by xnico31** [comment]
i have a issue to 

api.leboncoin.fr/finder/search

when you send the api request he return this. 

{"url":"https://c.datado.me/captcha/?initialCid=AHrlqAAAAAMAnpLzB0wHSA4ABTP5qA==&hash=05B30BD9055986BD2EE8F5A199D973&t=fe"}

But this url work but only for specific ID not a search 
https://api.leboncoin.fr/finder/classified/"+id

if you find a way to do search again ;) 

best

**Comment by alexismoreau** [comment]
you got banned from LBC, see #53

**Comment by Skymirrh** [comment]
@xnico31 Not sure it's the same issue as OP, see #53 for details relevant to your issue.

**Comment by alexismoreau** [comment]
@Skymirrh  Using your PR doesn't fix on my production setup, but works locally

**Comment by Skymirrh** [comment]
@alexismoreau Welp, too bad. I suggest we stick to #53 for discussing potential fixes so as to keep it in one place.

**Comment by xnico31** [comment]
I tried to change ip, serveur proxy same issue i don't think i'm ban

**Comment by tdurieux** [comment]
I look at the https://www.leboncoin.fr again and it seems they made some changes to the website to increase the security. 
I, unfortunately, don't have a lot of time to investigate on this :/

@xnico31 you should look at the header of your requests and how frequently you do it.

Maybe it is your server provider that has been blocked.

**Comment by ronyrun** [comment]
Same error here... 

Get result : {
    "url": "https://c.datado.me/captcha/?initialCid=*****************==&hash=****************&t=fe"
}

Header on chrome is : 

api_key: ba0c2dad52b3ec
Content-Type: application/json
Referer: https://www.leboncoin.fr/recherche/?******************
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

I think it's about a cookie of c.datado.me but not sure....

**Comment by tdurieux** [comment]
I see that you are missing several headers:
- cookies of datadom
- encoding type
- origin

**Comment by ronyrun** [comment]
Thank you @tdurieux,

I tried on Postman with same error, I look at the #53  issue.


![image](https://user-images.githubusercontent.com/7273443/63655508-ffa51780-c788-11e9-82de-bf88592e5c5c.png)

**Comment by tdurieux** [comment]
You cannot use `*` value, you can look at the one used in this repo: https://github.com/tdurieux/leboncoin-api/commit/456d955747cec2f6005f7872e9bdaec7fc194339#diff-50e3aa130a4f97a42ee2cf111c7b1d9dR5

**Comment by ronyrun** [comment]
thanks @tdurieux ,

I red about the Cookie to add. 

I tried that, without success : 

![image](https://user-images.githubusercontent.com/7273443/63655583-f9636b00-c789-11e9-986a-f272c694feb5.png)

I'm gonna read about the datadome cookie I guess :/

**Comment by regarde** [comment]
Hi everyone, it look likes Leboncoin adjusted their Datadome settings, the current headers does not work anymore on my end. Any luck on yours?

**Comment by stanicboris** [comment]
Yep, I don't know if my IP is the problem but none of the solutions I've found are working anymore.

**Comment by tdurieux** [comment]
I don't have issues with the library (at least by doing only one request) but I am currently in the US, this may impact the results.

**Comment by regarde** [comment]
You're right, the library is working fine. I made further tests and it's an IP address issue. I was using Luminati and the proxy got detected/banned by Datadome.

**Comment by Aambro** [comment]
I am doing searches every 20 minutes apart from 00-06 hours and after getting results for few searches it then stops returning results. I get results again after few hours for few times and then stops again.

 I would love to get them more often and I believe I'm missing something. Likely I don't know how to set cookie correctly or something else? 

Could anyone give me a hint of what I'm missing and in case I need to put in some data from chrome, what data would that be? 
![Screenshot_20191218-185605_JuiceSSH](https://user-images.githubusercontent.com/3326868/71110972-a72ad780-21c8-11ea-94a9-7ec2607d4ad3.jpg)
