### ISSUE TITLE
Sample usage

### ISSUE THREAD

**Issue by fusiller** [tdurieux/leboncoin-api#6]
Dear Thomas,
For some reason the usage sample you created does not produce any output for me. I needed to create a .then(function(data) ... to handle the result.
I am not very familiar with promises (more an old style callback person) but are you sure your lib is actually supporting both callbacks and promises ?

**Comment by tdurieux** [comment]
Yes, my bad.
It was late when I create this usage sample...

**Comment by tdurieux** [comment]
This is not a best practice to support callback and promise in a library.
It's a lot of code to handle this feature and I don't want to add complexity to this library, sorry.

**Comment by fusiller** [comment]
Thank you for the offer, it will not be necessary. I could start using it efficiently.
Your code is very clean anyway and easy to read if necessary.
I raised issues with the intention to thank you and encourage you :)

**Comment by tdurieux** [comment]
> Thank you for the offer, it will not be necessary. I could start using it efficiently.
I will publish it anyway in  few days

> Your code is very clean anyway and easy to read if necessary.
Thanks

> I raised issues with the intention to thank you and encourage you :)
It works...
