### ISSUE TITLE
Images are not extracted

### ISSUE THREAD

**Issue by yns01** [tdurieux/leboncoin-api#9]
Hello,

It seems that only the first picture is extracted for all house/apartments rentals : 
http://www.leboncoin.fr/locations/930287312.htm?ca=21_s
Looking at the code:
> 
>     $(".thumbnails .item_imagePic > img").each(function (index, elem) {
>         images.push($(elem).attr('src').replace("thumbs",'images'));
>      });
>  
>      if(images.length == 0) {
>       images.push($(".item_image.big > img").attr('src'));
>      }

In the page source there are no such classes.

**Comment by tdurieux** [comment]
close with 3d283980b3023566ce59af6b7b813adf7d69d2e4
